spring:
  application:
    name: pledge-app-${server.port}
  datasource:
    url: jdbc:h2:./data/pr/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  redis:
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 4
        min-idle: 1
    timeout:  PT20S
    sentinel:
      master: mymaster
      nodes: 18.1.33.118:26379


server:
  port: 8091

axon:
  axonserver:
    servers: localhost
  distributed:
    enabled: true
  serializer:
    general: xstream
    messages: xstream
    events: xstream
  aggregate:
  snapshot:
    event:
      count:
        threshold: 20
  event:
    parallel: 2
  command:
    retry:
      max-count: 5
      interval: 1000
      executor:
        count: 2

generator:
  workerId: 2

logging:
  level:
    root: info
    fund:
      investment: debug



