spring:
  application:
    name: trade-app-${server.port}
    datasource:
    url: jdbc:h2:./data/trade/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.221.195:3306/trade?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
server:
  port: 7081
logging:
  level:
    root: info
    fund:
      investment: debug
axon:
  axonserver:
    servers: 192.168.221.195

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson

  snapshot:
    event:
      count:
        threshold: 2
  event:
    parallel: 2
  command:
    retry:
      max-count: 5
      interval: 1000
      executor:
        count: 2
    
generator:
  workerId: 2



