spring:
  application:
    name: instruction-exchange-app-${server.port}
  datasource:
    url: jdbc:h2:./data/instruction/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080

logging:
  level:
    root: info
    fund:
      investment: debug
snapshot:
  event:
    count:
      threshold: 2

axon:
  axonserver:
    servers: 192.168.221.195

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson





