spring:
  application:
    name: dist-app-${server.port}
  datasource:
    url: jdbc:h2:./data/distribution/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
server:
  port: 9081

axon:
  axonserver:
#    servers: 192.168.221.195
    servers: localhost

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson

generator:
  workerId: 3



