spring:
  application:
    name: dist-app-${server.port}
  datasource:
    url: jdbc:h2:./data/distribution/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.221.195:3306/distribution_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root123
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
server:
  port: 9081

axon:
  axonserver:
#    servers: 192.168.221.195
    servers: 192.168.43.135

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson

generator:
  workerId: 3



