spring:
  application:
    name: order-app-${server.port}
  datasource:
    url: jdbc:h2:./data/trade/es/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  #    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
server:
  port: 7080
logging:
  level:
    root: info
    fund:
      investment: debug
axon:
  axonserver:
    servers: 192.168.43.135

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson

snapshot:
  event:
    count:
      threshold: 2
    
generator:
  workerId: 2



