
spring:
  application:
    name: book-server
  datasource:
    url: jdbc:h2:./data/book/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
server:
  port: 8091
logging:
  level:
    root: info
    fund:
      investment: debug
axon:
  axonserver:
    servers: 192.168.221.195

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson


