spring:
  application:
    name: instruction-exchange-app-${server.port}
  datasource:
    url: jdbc:h2:./data/instruction/es/database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.221.195:3306/instruction?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root123
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect:
#          storage_engine: innodb
    generate-ddl: true
server:
  port: 8080

logging:
  level:
    root: info
    fund:
      investment: debug
snapshot:
  event:
    count:
      threshold: 2

axon:
  axonserver:
#    servers: 192.168.221.195
    servers: localhost

  distributed:
    enabled: true
  serializer:
    general: jackson
    messages: jackson
    events: jackson





